version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: boston-house-price
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$(aws configure get region || echo $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo Repo URI: $REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPO_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  discard-paths: no
